version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "4000:4000"
    command: npm run dev
    environment:
      - MONGO_URL=mongodb://mongo/heapoverflow
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017-27017"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - "./client:/usr/src/app/client"
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - backend
